[BitTorrent]
Session\BTProtocol=Both
Session\DefaultSavePath=/downloads
Session\Port=8999
Session\TempPath=/downloads/temp
Session\TempPathEnabled=true
Session\UseRandomPort=false

[LegalNotice]
Accepted=true

[Preferences]
WebUI\HostHeaderValidation=false
WebUI\Port=8080
WebUI\Username=admin
